### ISSUE TITLE
Service creation failes due to "instance was last in '' state, BOSH task 0"

### ISSUE THREAD

**Issue by hfrenzel** [blacksmith-community/blacksmith#20] opened 2020-03-25 22:08 UTC
While deploying a new service via blacksmith, the deployment was done fine, but the service status stalls with `create in progress`.

Trying to debug shows the following:
```
2020-03-25 11:41:13.986 DEBUG  [ad0106c4-03b9-4717-9ae6-a90b3e1ecdb7 postgresql/postgresql-small] deployment started, BOSH task 5788039
2020-03-25 11:41:13.986 DEBUG  [ad0106c4-03b9-4717-9ae6-a90b3e1ecdb7 postgresql/postgresql-small] tracking service instance in the vault 'db' index
2020-03-25 11:41:13.989 DEBUG  [ad0106c4-03b9-4717-9ae6-a90b3e1ecdb7 postgresql/postgresql-small] updating service status in the vault
2020-03-25 11:41:13.990 DEBUG  [vault track ad0106c4-03b9-4717-9ae6-a90b3e1ecdb7] tracking action 'provision', task 5788039
2020-03-25 11:41:13.992 DEBUG  [ad0106c4-03b9-4717-9ae6-a90b3e1ecdb7 postgresql/postgresql-small] started provisioning
2020-03-25 11:41:17.379 DEBUG  [ad0106c4-03b9-4717-9ae6-a90b3e1ecdb7] last-operation check received; checking state of service deployment
2020-03-25 11:41:17.380 DEBUG  [ad0106c4-03b9-4717-9ae6-a90b3e1ecdb7] instance was last in '' state, BOSH task 0
2020-03-25 11:41:17.380 ERROR  [ad0106c4-03b9-4717-9ae6-a90b3e1ecdb7] invalid state '' found in the vault
2020-03-25 11:42:19.854 DEBUG  [ad0106c4-03b9-4717-9ae6-a90b3e1ecdb7] last-operation check received; checking state of service deployment
2020-03-25 11:42:19.856 DEBUG  [ad0106c4-03b9-4717-9ae6-a90b3e1ecdb7] instance was last in '' state, BOSH task 0
2020-03-25 11:42:19.856 ERROR  [ad0106c4-03b9-4717-9ae6-a90b3e1ecdb7] invalid state '' found in the vault
```

The tracked action seems to be correct in vault:
```
# /var/vcap/packages/safe/bin/safe get secret/ad0106c4-03b9-4717-9ae6-a90b3e1ecdb7/task
--- # secret/ad0106c4-03b9-4717-9ae6-a90b3e1ecdb7/task
action: provision
params: '{}'
task: "5788039"

```
The deployment:
```
$ bosh vms -d postgresql-small-ad0106c4-03b9-4717-9ae6-a90b3e1ecdb7
Using environment 'https://10.0.1.6:25555' as user 'admin'

Task 5793461. Done

Deployment 'postgresql-small-ad0106c4-03b9-4717-9ae6-a90b3e1ecdb7'

Instance                                         Process State  AZ  IPs        VM CID                                VM Type  Active
postgresql/631c443e-9056-4860-bb6d-735f34fa290f  running        z1  10.0.1.99  7e173ab2-0d2b-45f7-8ad1-9ab9297c82e3  default  true

1 vms

Succeeded
```

We're using `blacksmith-boshrelease` v1.1.0 and the example above was done with `postgresql-forge-boshrelease` v0.3.1, but with `redis-forge-boshrelease` v0.4.2 it's the same result.

I can't find what could be wrong here, so any help or hints is appreciated.

**Comment by jhunt** [comment] 2020-03-27 13:16
At first blush, it sounds like the instance information is not found in the Vault, given that `''` and `0` are both zero-values in Golang territory.  Since Blacksmith is trying to look up a BOSH task with ID 0, it's never going to see that task 5793461 is actually happy and healthy.

@krutten can you take v1.1.0 for a spin and see if you can reproduce this issue?

**Comment by wayneeseguin** [comment] 2022-04-22 13:29
Unable to reproduce. If this is still an issue please come back, closing due to age.

**Closed as completed by wayneeseguin** 2022-04-22 13:29 UTC
